services:
  - type: web
    name: viddy-downloader
    env: python
    buildCommand: pip install -r requirements_web.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 120 wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py